# Generated by Django 2.2.8 on 2020-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='website.Picture'),
        ),
    ]
