# Generated by Django 2.2.8 on 2020-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200105_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('small_about', models.TextField(max_length=1000)),
                ('full_about', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
