# Generated by Django 2.2.8 on 2020-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_sitesetting_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
