# Generated by Django 2.2.8 on 2020-01-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_article_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentarticle',
            old_name='post',
            new_name='article',
        ),
    ]
