# Generated by Django 2.2.8 on 2020-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_fa',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_ru',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='full_about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='full_about_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='full_about_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='small_about_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='small_about_fa',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='small_about_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
