# Generated by Django 2.2.8 on 2020-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200110_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address_fa',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='small_about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='small_about_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='small_about_fa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='small_about_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
