# Generated by Django 2.2.8 on 2020-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
