# Generated by Django 2.2.8 on 2020-01-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_product_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ru',
        ),
    ]
